// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGfXGi8FYKoXv9SY5Db5KlRUNB6vq0Ba0',
    appId: '1:125653867491:web:21b88aa9e3ef9fb01e9ed6',
    messagingSenderId: '125653867491',
    projectId: 'fir-authentication-f693e',
    authDomain: 'fir-authentication-f693e.firebaseapp.com',
    storageBucket: 'fir-authentication-f693e.appspot.com',
    measurementId: 'G-TK95WX0DGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqgishRQw8aKsVx2GJOgSY9uYji3XUnRk',
    appId: '1:125653867491:android:9ce0349b291b70191e9ed6',
    messagingSenderId: '125653867491',
    projectId: 'fir-authentication-f693e',
    storageBucket: 'fir-authentication-f693e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxy2bM-U0wdEhx3ixSZsX_d3DBQMPSHa8',
    appId: '1:125653867491:ios:c09d380c214a0b381e9ed6',
    messagingSenderId: '125653867491',
    projectId: 'fir-authentication-f693e',
    storageBucket: 'fir-authentication-f693e.appspot.com',
    iosBundleId: 'com.example.authenticationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxy2bM-U0wdEhx3ixSZsX_d3DBQMPSHa8',
    appId: '1:125653867491:ios:c09d380c214a0b381e9ed6',
    messagingSenderId: '125653867491',
    projectId: 'fir-authentication-f693e',
    storageBucket: 'fir-authentication-f693e.appspot.com',
    iosBundleId: 'com.example.authenticationFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGfXGi8FYKoXv9SY5Db5KlRUNB6vq0Ba0',
    appId: '1:125653867491:web:1416c948188e05a11e9ed6',
    messagingSenderId: '125653867491',
    projectId: 'fir-authentication-f693e',
    authDomain: 'fir-authentication-f693e.firebaseapp.com',
    storageBucket: 'fir-authentication-f693e.appspot.com',
    measurementId: 'G-HWHY0WFFJP',
  );
}
